### ISSUE TITLE
Handle InfluxDB::Errors Properly

### ISSUE THREAD

**Issue by jonmchan** [fangli/fluent-plugin-influxdb#16]
I found an issue where the fluent-plugin-influxdb does not handle fatal influxdb errors well. I was switching from calling influxdb direct and using fluent so we had the time field set, but this plugin tried to set it too. This caused influxdb to throw an error:

```
2015-06-05 01:21:38 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2015-06-05 01:21:38 +0000 error_class="InfluxDB::Error" error="Cannot have duplicate field names" plugin_id="object:3fcef1e5c70c"
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/influxdb-0.1.8/lib/influxdb/client.rb:234:in `block in post'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/influxdb-0.1.8/lib/influxdb/client.rb:264:in `call'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/influxdb-0.1.8/lib/influxdb/client.rb:264:in `connect_with_retry'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/influxdb-0.1.8/lib/influxdb/client.rb:227:in `post'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/influxdb-0.1.8/lib/influxdb/client.rb:170:in `_write'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/influxdb-0.1.8/lib/influxdb/client.rb:163:in `write_point'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-influxdb-0.1.4/lib/fluent/plugin/out_influxdb.rb:52:in `block in write'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/buf_memory.rb:61:in `feed_each'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/buf_memory.rb:61:in `msgpack_each'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-influxdb-0.1.4/lib/fluent/plugin/out_influxdb.rb:49:in `write'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:304:in `pop'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:321:in `try_flush'
  2015-06-05 01:21:38 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:140:in `run'
2015-06-05 01:21:39 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2015-06-05 01:21:40 +0000 error_class="InfluxDB::Error" error="Cannot have duplicate field names" plugin_id="object:3fcef1e5c70c"
```

When this happens, the plugin gets into a retry loop state that prohibits any new messages from being relayed correctly. Instead of trying to resend the buffer, these types of messages should be logged and discarded. This will allow valid messages to continue being logged.

**Comment by repeatedly** [comment]
Hmm... it means your record is `{"time":"...","k1":"v1",...}`?

**Comment by jonmchan** [comment]
Yes, my record was that. I fixed it, but td-agent went into a state where it would no longer send any requests. I had to restart td-agent after that to get it to start working again.

**Comment by repeatedly** [comment]
I just wrote a simple patch for this case.
Could you test a patch?

**Comment by jonmchan** [comment]
@repeatedly I tested it and it works. You can merge the other PR. 

I think it'd be nice though to handle the error states a little more intelligently and drop the messages that are permanent errors.

**Comment by repeatedly** [comment]
> I think it'd be nice though to handle the error states a little more intelligently and drop the messages that are permanent errors.

I agree but influxdb-ruby seems to raise InfluxDB::Error with error message from influx database.
Do you have a list of error messages?

**Comment by jonmchan** [comment]
I do not have a complete list of error messages, but I think a good starting point would be the influxdb-ruby errors.

https://github.com/influxdb/influxdb-ruby/blob/daab9282427641cb222d0939c2f78882c0ec14d5/lib/influxdb/errors.rb

JSONParserError and AuthenticationError are fatal errors and the data should not be resent. The others we can flush out in further iterations of the plugin.

**Comment by repeatedly** [comment]
> JSONParserError

It doesn't appear in influxdb code.

> AuthenticationError

Hmm... how about calling get_database_list like API to check user/password at start phase?
If failed, fluentd doesn't start.
